spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/mingcanchen/others.git
          #username:
          #password:
          search-paths: server-config
  application:
    name: ch11-2-config-server
server:
    port: 9090