spring:
  application:
    name: ribbon-loadbalancer
server:
  port: 7777
eureka:
  client:
    service-url:
      defaultZone: http://${eureka.host:127.0.0.1}:${eureka.port:8761}/eureka/
  instance:
    prefer-ip-address: true
