spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/mingcanchen/others.git
          search-paths: sc-redefine-config
  application:
    name: ch12-9-config-server-high-availability
server:
    port: 9090

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/