apiVersion: v1
kind: ReplicationController
metadata:
  name: example-service
  namespace: springcloud-cn
  labels:
    app: example-service
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: example-service
    spec:
      containers:
      - name: example-service
        image: registry.cn-hangzhou.aliyuncs.com/springcloud-cn/ch22-3-2-example-service:0.0.1-SNAPSHOT
        imagePullPolicy: Always
        resources:
          requests:
            cpu: 100m
            memory: 256Mi
          limits:
            cpu: 1000m
            memory: 2Gi
        env:
          - name: PROFILE
            value: "default"
          - name: SERVER_PORT
            value: "8080"
          - name: JAVA_OPTS
            value: "
-server \
-XX:+PrintGCDetails \
-XX:+PrintTenuringDistribution \
-XX:+PrintGCTimeStamps \
-XX:+HeapDumpOnOutOfMemoryError \
-XX:HeapDumpPath=/ \
-Xloggc:/gc.log \
-XX:+UseGCLogFileRotation \
-XX:NumberOfGCLogFiles=5 \
-XX:GCLogFileSize=10M"
        ports:
          - name: http
            containerPort: 8080