apiVersion: v1
kind: Service
metadata:
  name: example-service
  namespace: springcloud-cn
  labels:
    service: example-service
spec:
  selector:
    app: example-service
  ports:
  - name: http
    port: 8080
    targetPort: 8080
  clusterIP: 10.96.0.8
  externalIPs:
    - 192.168.99.101