spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/mingcanchen/others.git
          #username:
          #password:
          search-paths: server-config
  application:
    name: sc-config-git
server:
    port: 9090