// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: HiService.proto

package com.ming;

public interface HelloResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.ming.HelloResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string greeting = 1;</code>
   */
  String getGreeting();
  /**
   * <code>string greeting = 1;</code>
   */
  com.google.protobuf.ByteString
      getGreetingBytes();
}
