// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: HiService.proto

package com.ming;

public interface HelloRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.ming.HelloRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string name = 1;</code>
   */
  String getName();
  /**
   * <code>string name = 1;</code>
   */
  com.google.protobuf.ByteString
      getNameBytes();

  /**
   * <code>int32 age = 2;</code>
   */
  int getAge();

  /**
   * <code>repeated string hobbies = 3;</code>
   */
  java.util.List<String>
      getHobbiesList();
  /**
   * <code>repeated string hobbies = 3;</code>
   */
  int getHobbiesCount();
  /**
   * <code>repeated string hobbies = 3;</code>
   */
  String getHobbies(int index);
  /**
   * <code>repeated string hobbies = 3;</code>
   */
  com.google.protobuf.ByteString
      getHobbiesBytes(int index);

  /**
   * <code>map&lt;string, string&gt; tags = 4;</code>
   */
  int getTagsCount();
  /**
   * <code>map&lt;string, string&gt; tags = 4;</code>
   */
  boolean containsTags(
          String key);
  /**
   * Use {@link #getTagsMap()} instead.
   */
  @Deprecated
  java.util.Map<String, String>
  getTags();
  /**
   * <code>map&lt;string, string&gt; tags = 4;</code>
   */
  java.util.Map<String, String>
  getTagsMap();
  /**
   * <code>map&lt;string, string&gt; tags = 4;</code>
   */

  String getTagsOrDefault(
          String key,
          String defaultValue);
  /**
   * <code>map&lt;string, string&gt; tags = 4;</code>
   */

  String getTagsOrThrow(
          String key);
}
