spring:
  application:
    name: demo-provider

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

dubbo:
  application:
    name: demo-provider
  registry:
    address: zookeeper://127.0.0.1:2181
  protocol:
    name: dubbo
    port: 20880
  scan:
    basePackages: cn.springcloud.book