spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/mingcanchen/others.git
          search-paths: sc-redefine-config
          force-pull: true
  application:
    name: ch12-7-config-server-auth-jwt

  security:
    user:
      name: root
      password: 123

server:
    port: 9090
