server:
  port: 8081

logging:
  level:
    org.springframework.cloud.gateway: TRACE
    org.springframework.http.server.reactive: DEBUG
    org.springframework.web.reactive: DEBUG
    reactor.ipc.netty: DEBUG


#开启actuator管理api，后面要关闭
management:
  endpoints:
    web:  # http://localhost:8080/actuator/gateway/routes
      exposure:
        include: "*"
#spring:
#  cloud:
#    gateway:
#      routes:
#      - id: after_route
#         uri: http://www.baidu.com
#         predicates:
#         - After=2019-01-10T12:52:10.163+08:00[Asia/Shanghai]

spring:
  cloud:
    gateway:
      routes:
        - id: after_route
          uri: http://baidu.com:80/
          predicates:
            - After=2019-01-10T16:14:52.76+08:00[Asia/Shanghai]