apiVersion: v1
kind: Service
metadata:
  name: config-server
  namespace: springcloud-cn
  labels:
    service: config-server
spec:
  selector:
    app: config-server
  ports:
  - name: http
    port: 8888
    targetPort: 8080
  clusterIP: 10.96.0.2
  externalIPs:
    - 192.168.99.101