apiVersion: v1
kind: Service
metadata:
  name: spring-admin
  namespace: springcloud-cn
  labels:
    service: spring-admin
spec:
  selector:
    app: spring-admin
  ports:
  - name: http
    port: 8002
    targetPort: 8080
  clusterIP: 10.96.0.7
  externalIPs:
    - 192.168.99.101