apiVersion: v1
kind: Service
metadata:
  name: turbine
  namespace: springcloud-cn
  labels:
    service: turbine
spec:
  selector:
    app: turbine
  ports:
  - name: http
    port: 8001
    targetPort: 8080
  clusterIP: 10.96.0.6
  externalIPs:
    - 192.168.99.101