spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/mingcanchen/{application}
          #username:
          #password:
          search-paths: server-config
  application:
    name: ch12-1-config-server-placeholders
server:
    port: 9090
logging:
  level:
    root: debug
