server:
  port: 9018

spring:
  application:
    name: ch12-10-config-client-apollo

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

apollo:
  bootstrap:
    enabled: true
    namespaces: application
  meta: http://localhost:8080
