server.port: 8082
spring:
  application:
    name: ch18-6-3-gateway


logging:
  level:
    #org.springframework.cloud.gateway: debug
    com.ming.gateway.filter: debug


#开启端点
management:
  endpoints:
    web:
      exposure:
        include: '*'
  security:
    enabled: false